lms/lms/conta/urls.py
from django.conf.urls import url

from .views import *

app_name = 'conta'
urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^login/$', login_view, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^register/$', RegistrationView.as_view(), name="register"),
]

lms/lms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('lms.core.urls')),
    url(r'^users/', include('lms.conta.urls')),
    url(r'^aluno/', include('lms.aluno.urls')),
    url(r'^professor', include('lms.professor.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lms/lms/aluno/models.py
from django.db import models
from lms.conta.models import User
from datetime import datetime
import random



def gera_ra():
    #FUNÇÃO PARA GERAR RA AUTOMATICO
    x = datetime.now()
    y = str(x.year)
    return (y[2:]+"%i"%(random.randint(1000,90000)))


class Aluno(User):
    '''
    Classe usuários/Aluno
    '''
    ra = models.CharField(max_length=7, default=gera_ra(),unique=True, null=False, blank=False)
    nome_completo = models.CharField(max_length=100, null=False, blank=False)
    contatos = models.CharField(max_length=11, null=False, blank=False)


    class Meta:
        verbose_name = 'Aluno'
        verbose_name_plural = 'Alunos'

lms/lms/conta/models.py
import re

from django.db import models
from django.core import validators
from django.utils import timezone
from django.core.mail import send_mail

from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager



class UserManager(BaseUserManager):
    '''
    Classes de criação de usuário padrão
    '''
    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        if not username:
          raise ValueError(_('The given username must be set'))
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                 is_staff=is_staff, is_active=True,
                 is_superuser=is_superuser, last_login=now)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False,
                 **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        user=self._create_user(username, email, password, True, True,
                 **extra_fields)
        user.is_active=True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    '''
    classe de usuário custom
    '''
    username = models.CharField(_('username'), max_length=15, unique=True,
        help_text=_('Required. 15 characters or fewer. Letters, \
                    numbers and @/./+/-/_ characters'),
        validators=[
                    validators.RegexValidator(
                                            re.compile('^[\w.@+-]+$'),
                                            _('Enter a valid username.'),
                                            _('invalid'))])

    email = models.EmailField(_('email address'), max_length=255, unique=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin site.'))

    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as active. \
                    Unselect this instead of deleting accounts.'))


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


    def get_short_username(self):
        return self.username

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

lms/lms/conta/forms.py
# Arquivo: apps/users/forms.py'

from django.contrib.auth.forms import UserCreationForm

from lms.aluno.models import Aluno



class CustomUserCreationForm(UserCreationForm):
    '''
    Customizando os campos do formulario de cadastro aluno
    '''
    class Meta:
        model = Aluno
        fields = ['username','email','nome_completo','contatos']

lms/lms/conta/views.py
# coding=utf-8
from django.shortcuts import render
from django.views.generic import CreateView
from django.http import HttpResponseRedirect
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse_lazy, reverse

from .forms import CustomUserCreationForm


def home(request):
    return render(request, 'conta/home.html')


def login_view(request, *args, **kwargs):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('conta:home'))

    kwargs['extra_context'] = {'next': reverse('aluno:home')}
    kwargs['template_name'] = 'conta/login.html'
    return login(request, *args, **kwargs)


def logout_view(request, *args, **kwargs):
    kwargs['next_page'] = reverse('conta:login')
    return logout(request, *args, **kwargs)


class RegistrationView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('conta:login')
    template_name = "conta/register.html"


'''

--------------------------------------------------------------------------
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

def cadastro(request, template_name='conta/cadastro_aluno.html'):
    if request.method == "POST":
        username == request.POST['username']
        email == request.POST['email']
        password == request.POST['password']
        user = User.objects.create_user(username, email, password)
        return redirect('')
    return render(request, template_name, {})

def login(request, template_name='conta/login.html'):
    return render(request, template_name)


'''

lms/lms/conta/templates/conta/cadastro_aluno.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

  </header>

<h4 class="center"><p>Cadastro</p></h4>
<div class="row container">

  <form class="col s12 m12 l12 container-fluid">{% csrf_token %}

  	<div class="row">
  	  <div class="input-field col s12 m5 l5">
  			<input name="username" placeholder="Crei um Username" type="text" class="validate" required>
  			<label>Usuário</label>
  		</div>

    <div class="input-field col s12 m5 l5">
        <input type="email" name="email" placeholder="Digite um e-mail"class="validate" required>
        <label>E-mail</label>
      </div>
    </div>

    <div class="row">
      	<div class="input-field col s12 m5 l5">
      		<input type="password" name="password" placeholder="Digite uma Senha" class="validate" required>
      		<label>Senha</label>
      	</div>

		<div class="input-field col s12 m5 l5">
			<select name="tipo_usuario">
				<option value="" disabled selected>Escolha uma opção</option>
				<option value="administrador">Administrador</option>
				<option value="usuario">Usuário</option>
			</select>
			<label> Tipo de Usuário</label>
		</div>
    	<!--	<div class="input-field col s12 m5 l5">
    			<select>
    				<option value="" disabled selected>Sigla Curso</option>
    				<option value="graduacao_adm">ADM - Graduacao em Administração</option>
    				<option value="graduacao_ads">ADS - Graduacao em Análise e Desenvolvimento de Sistemas</option>
    				<option value="graduacao_bd">BD - Graduacao em Banco de Dados</option>
    				<option value="graduacao_gti">GTI - Graduacao em Gestao da Tecnologia da Informação</option>
    				<option value="graduacao_jd">JD - Graduacao em Jogos Digitais</option>
    				<option value="graduacao_pg">PG - Graduacao em Processos Gerenciais</option>
    				<option value="graduacao_mm">MM - Graduacao em Multimidia</option>
    				<option value="graduacao_rc">RC - Graduacao em Redes de Computadores</option>
    				<option value="graduacao_si">SI - Graduacao em Sistemas de Informação</option>
    			</select>
    		</div> -->
      </div>

      <div class="row">
    		<div class="input-field col s12 m5 l5">
    			<button class="btn waves-effect waves-light" type="submit" name="action">Cadastrar
    				<!-- <i class="material-icons right">send</i> -->
    			</button>
    		</div>
    	</div>
    </form>
</div>

{% endblock %}

lms/lms/conta/templates/conta/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}

</header>
<p>Seja bem vindo {% if user.is_authenticated %}{{ user.first_name }}{% else %}usuário anônimo{% endif %}</p>

{% if user.is_authenticated %}
<p><a href="{% url 'conta:logout' %}">Logout</a>.</p>
{% else %}
<p><a href="{% url 'conta:register' %}">Registre-se</a>.</p>
<p><a href="{% url 'conta:login' %}">Login</a>.</p>
{% endif %}

{% endblock %}

lms/lms/conta/templates/conta/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}

</header>



    <form class="row container" method="post" action="{{ request.path }}{% if next %}?next={{ next }}{% endif %}">

        {% csrf_token %}
            <br>
            <h3 class="center">Área de Login</h3>

                {{ form.non_field_errors }}

                {% for field in form %}

                <div class="group col s6 m6 l6 center">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>

                {% endfor %}

                <div class="center col s12">
                    <button type="submit" class="btn waves-effect waves-light">Login</button>
                </div>

        </form>

    </div>

    <br><br><br><br>
    <div class="row container">
        <h4 class="center">Ainda não é cadastrado ?</h4>
        <p class="center">
            <a class="btn  teal pulse" href="{% url 'conta:register' %}">
                Clieque aqui e Cadastre-se
            <i class="material-icons">edit</i>
            </a>
        </p>
    </div>


{% endblock %}

lms/lms/conta/templates/conta/register.html
{% extends "base.html" %}

{% load static %}

{% block content %}
</header>
<br>

<div class="container-center">

            <form class="row container" method="post">

                {% csrf_token %}
                <h1 class="center">Cadastre-se</h1>
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                    <div class="group col s12 m5 l6">
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                    </div>
                    {% endfor %}

                    <div class="center">
                        <button type="submit" class="btn waves-effect waves-light">Cadastrar</button>
                    </div>

                </fieldset>

            </form>

    </div>
</div>


<br>


<br>
{% endblock %}
<!--
<div class="container">
    <h4 class="center">Cadastre-se</h4>

    <br>
    <br>
    <form class="center" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="input-field col s12 m5 l6">
            <input type="text" name="username" placeholder="Digite um username" id="id_username" required autofocus maxlength="15" />
            <label for="{{form.id_username}}">Usuário:</label>

        </div>

        <div class="input-field col s12 m5 l6">
            <input type="email" name="email" placeholder="Digite seu E-mail" id="id_email" required maxlength="255" />
            <label for="{{form.id_email}}">Endereço de email:</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s7">
            <input type="text" name="nome_completo" id="id_nome_completo" required placeholder="Digite seu Nome">
            <label for="{{form.id_nome_completo}}">Nome:</label>
        </div>

        <div class="input-field col s5">
            <input type="text" name="contatos" placeholder="Telefone" id="id_contatos" required maxlength="11" />
            <label for="{{fomr.id_contatos}}">Telefone:</label>
        </div>
    </div>

    <div class="row">
        <div class="input-field col s12 m5 l6">
            <input type="password" name="password" placeholder="Digite uma Senha" id="id_password" required>
            <label for="{{form.id_password}}">Senha:</label>
        </div>

        <div class="input-field col s12 m5 l6">
            <input type="password" name="password2" placeholder="Confirme sua Senha" id="id_password2" required  />
            <label for="{{form.id_password2}}">Confirmação de senha:</label>

        </div>
    </div>
        <button type="submit" class="btn btn-warning">Register</button>
    </form>
</div>
<br> -->